"""Emit PGFPlots figure sources consumed by the paper.

Outputs:
  paper/figures/fig_elo_curves.tex   --- one \\begin{figure} with an
    Elo-claim trajectory scatter, coloured by language category.

No matplotlib / no images --- everything stays native TeX.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DATA = REPO / "data"
FIG = REPO / "paper" / "figures"
FIG.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(HERE))
from build_paper_tables import DISPLAY_LANG  # type: ignore

# Language categories used in the paper, keyed by display language.
CATEGORY = {
    # mainstream general-purpose
    "Python": "mainstream", "Java": "mainstream", "C": "mainstream",
    "C++": "mainstream", "C++ (DSL host)": "mainstream", "Rust": "mainstream",
    "Ruby": "mainstream", "JavaScript": "mainstream", "Mojo": "mainstream",
    # specialized / academic / symbolic
    "APL": "specialized", "Icon": "specialized", "Lean 4": "specialized",
    "OCaml": "specialized", "Why3→C": "specialized", "Why3→OCaml": "specialized",
    "Rocq→OCaml": "specialized",
    # domain-specific / markup
    "LaTeX": "dsl-markup", "LaTeX (TeX)": "dsl-markup", "CSS/HTML": "dsl-markup",
    "SQL": "dsl-markup",
    # legacy
    "COBOL": "legacy", "Assembly": "legacy",
    # esoteric
    "Brainfuck": "esoteric",
}

# PGFPlots-friendly colour per category.
CAT_COLOR = {
    "mainstream":  "blue!70!black",
    "specialized": "orange!80!black",
    "dsl-markup":  "purple!70!black",
    "legacy":      "red!70!black",
    "esoteric":    "green!45!black",
}

CAT_LABEL = {
    "mainstream":  "mainstream general-purpose",
    "specialized": "specialized / academic",
    "dsl-markup":  "domain-specific / markup",
    "legacy":      "legacy",
    "esoteric":    "esoteric",
}


def display_language(overview_row: dict) -> str:
    return DISPLAY_LANG.get(overview_row["name"], overview_row.get("primary_language") or "—") \
        .replace("$\\to$", "→") \
        .replace("$\\times$", "×")


def main() -> None:
    cross = json.loads((DATA / "cross_trajectory.json").read_text())
    ov = {o["name"]: o for o in json.loads((DATA / "overview.json").read_text())}
    # Collect engines with at least 2 Elo-claim points (a visible curve).
    series: list[dict] = []
    for name, sig in cross.items():
        curve = sig.get("elo_curve") or []
        if len(curve) < 2:
            continue
        n_steps = sig.get("n_steps", 1) or 1
        lang = display_language(ov.get(name, {"name": name}))
        cat = CATEGORY.get(lang, "specialized")
        pts = [(idx / n_steps, elo) for idx, elo in curve]
        shape = sig.get("elo_shape") or "unknown"
        series.append({"name": name, "lang": lang, "cat": cat, "pts": pts, "shape": shape})
    series.sort(key=lambda s: (s["cat"], s["name"]))

    # Emit PGFPlots.
    L: list[str] = []
    L.append("% Auto-generated by scripts/gen_figures.py --- do not edit by hand.")
    L.append(r"\begin{figure}[ht]")
    L.append(r"\centering")
    L.append(r"\begin{tikzpicture}")
    L.append(r"\begin{axis}[")
    L.append(r"  width=0.95\linewidth, height=0.55\linewidth,")
    L.append(r"  xlabel={Session progress (step index / total steps)},")
    L.append(r"  ylabel={Agent-claimed Elo (from assistant text)},")
    L.append(r"  xmin=0, xmax=1.02,")
    L.append(r"  ymin=0, ymax=2800,")
    L.append(r"  grid=both, grid style={gray!20},")
    L.append(r"  legend style={font=\tiny, at={(0.02,0.98)}, anchor=north west, draw=none, fill=white, fill opacity=0.75, text opacity=1},")
    L.append(r"  legend columns=1,")
    L.append(r"  tick label style={font=\footnotesize},")
    L.append(r"  label style={font=\footnotesize},")
    L.append(r"  mark size=1.7pt,")
    L.append(r"]")
    # Aggregate by category for a single legend entry per category.
    # To do that cleanly, we add one \addplot per engine but only call
    # \addlegendentry for the first engine of each category.
    seen_cat: set[str] = set()
    for s in series:
        color = CAT_COLOR.get(s["cat"], "black")
        mark = {
            "mainstream":  "*",
            "specialized": "triangle*",
            "dsl-markup":  "square*",
            "legacy":      "diamond*",
            "esoteric":    "pentagon*",
        }.get(s["cat"], "*")
        dashed = ",dashed" if s["shape"] == "zigzag" else ""
        coords = " ".join(f"({x:.3f},{y})" for x, y in s["pts"])
        L.append(rf"  \addplot[color={color}, mark={mark}{dashed}, mark options={{fill={color}}}, thick] coordinates {{ {coords} }};")
        if s["cat"] in seen_cat:
            L.append(r"  \addlegendentry{}")
        else:
            L.append(rf"  \addlegendentry{{{CAT_LABEL[s['cat']]}}}")
            seen_cat.add(s["cat"])
    L.append(r"\end{axis}")
    L.append(r"\end{tikzpicture}")
    L.append(r"\caption{Agent-claimed Elo over normalized session progress, for engines with at least two Elo mentions in their transcripts. One polyline per engine; colour + marker shape by language category. \emph{Dashed} polylines mark zigzag trajectories (an Elo claim that dropped then recovered within the session, \Cref{sec:rq4:curve}). The mainstream general-purpose engines cluster near the top, rise monotonically, and cap around \elo{2000}--\elo{2200}; the legacy and domain-specific cells plateau at \elo{1000}--\elo{1600}; the esoteric row sits at the bottom. The zigzag engines are the ones where the agent caught and rolled back a regression mid-session --- a supervision signal that costs tokens but prevents strength loss.}")
    L.append(r"\label{fig:elo-curves}")
    L.append(r"\end{figure}")
    out = FIG / "fig_elo_curves.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}  ({len(series)} engine curves across {len(seen_cat)} categories)")


def emit_loc_strip() -> None:
    """Strip plot of total LOC per engine, one row per language category (log x-axis)."""
    import math

    # Engine data from tab_engines.tex (total LOC, files, display language).
    # Two outliers annotated: chess-ruby-codex (PGN data included) and
    # chess-why3-cc (generated C artefacts included).
    ENGINES: list[tuple[str, str, int, int]] = [
        # (name, display_lang, total_loc, files)
        ("chess-apl-codex54",            "APL",          3_652,   10),
        ("chess-assembly-codex",         "Assembly",    12_310,    9),
        ("chess-brainfuck",              "Brainfuck",    6_920,   56),
        ("chess-brainfuck-cc",           "Brainfuck",    7_879,   18),
        ("chess-purec",                  "C",            3_158,   28),
        ("chess-purec-codex",            "C",            3_095,   16),
        ("chess-cplusplus-claude",       "C++",          4_248,   28),
        ("cplusplus-chess",              "C++",          4_420,   34),
        ("COBOL-chess",                  "COBOL",        8_890,   76),
        ("chess-cobol-cc",               "COBOL",       11_578,    4),
        ("chess-css-codex",              "CSS/HTML",    38_684,   22),
        ("chess-css-codex-guided",       "CSS/HTML",     2_077,    4),
        ("chess-icon-codex",             "Icon",         3_217,   22),
        ("chess-java",                   "Java",         2_835,   22),
        ("chess-java-cc",                "Java",         4_884,   35),
        ("chess-latex-codex-replication","LaTeX",        5_222,   46),
        ("latex-chess-engine",           "LaTeX (TeX)", 41_185,   23),
        ("lean-chess",                   "Lean 4",       2_333,   15),
        ("chess-py",                     "Python",       3_890,   22),
        ("chess-py-cc",                  "Python",       2_995,   22),
        ("chess-Rocq",                   "Rocq→OCaml",   6_335,   51),
        ("chess-ruby-cc",                "Ruby",         2_964,   22),
        ("chess-ruby-codex",             "Ruby",       124_443,   43),
        ("chess-rust-cc",                "Rust",         5_872,   27),
        ("chess-rust-codex",             "Rust",         1_819,    8),
        ("chess-sql",                    "SQL",          2_016,   15),
        ("chess-why3-cc",                "Why3→C",      91_558,  234),
        ("chess-why3",                   "Why3→OCaml",   4_530,   46),
    ]

    # Map each engine to its category y-center (5=mainstream … 1=esoteric).
    Y_CENTER = {
        "mainstream":  5.0,
        "specialized": 4.0,
        "dsl-markup":  3.0,
        "legacy":      2.0,
        "esoteric":    1.0,
    }

    # Build per-category buckets sorted by LOC.
    from collections import defaultdict
    buckets: dict[str, list] = defaultdict(list)
    for name, lang, loc, files in ENGINES:
        cat = CATEGORY.get(lang, "specialized")
        buckets[cat].append((loc, files, lang, name))
    for cat in buckets:
        buckets[cat].sort(key=lambda t: t[0])

    # Assign y-jitter: spread evenly within ±0.38 per category.
    JITTER_HALF = 0.38
    pts: list[tuple[float, int, int, str, str, str]] = []  # (y, loc, files, lang, cat, name)
    for cat, items in buckets.items():
        n = len(items)
        yc = Y_CENTER[cat]
        for i, (loc, files, lang, name) in enumerate(items):
            if n == 1:
                jitter = 0.0
            else:
                jitter = -JITTER_HALF + i * (2 * JITTER_HALF / (n - 1))
            pts.append((yc + jitter, loc, files, lang, cat, name))

    # Build annotation list for notable outliers.
    ANNOTATE = {
        "chess-ruby-codex": r"Ruby (PGN data)",
        "chess-why3-cc":    r"Why3$\to$C (gen.\ C)",
        "chess-css-codex":  r"CSS/HTML",
        "latex-chess-engine": r"LaTeX (TeX)",
    }

    L: list[str] = []
    L.append("% Auto-generated by scripts/gen_figures.py --- do not edit by hand.")
    L.append(r"\begin{figure}[ht]")
    L.append(r"\centering")
    L.append(r"\begin{tikzpicture}")
    L.append(r"\begin{axis}[")
    L.append(r"  width=0.82\linewidth, height=0.35\linewidth,")
    L.append(r"  xmode=log,")
    L.append(r"  xlabel={Total lines of code (repository, log scale)},")
    L.append(r"  ylabel={},")
    L.append(r"  ytick={1,2,3,4,5},")
    L.append(r"  yticklabels={esoteric, legacy, domain-specific~/~markup, specialized~/~academic, mainstream general-purpose},")
    L.append(r"  ymin=0.35, ymax=5.65,")
    L.append(r"  xmin=1000, xmax=250000,")
    L.append(r"  xtick={1000,2000,5000,10000,20000,50000,100000},")
    L.append(r"  xticklabels={1k,2k,5k,10k,20k,50k,100k},")
    L.append(r"  grid=both, grid style={gray!20},")
    L.append(r"  tick label style={font=\footnotesize},")
    L.append(r"  label style={font=\footnotesize},")
    L.append(r"  mark size=2.2pt,")
    L.append(r"  legend style={font=\tiny, at={(0.98,0.02)}, anchor=south east, draw=none, fill=white, fill opacity=0.75, text opacity=1},")
    L.append(r"  legend columns=1,")
    L.append(r"]")

    seen_cat: set[str] = set()
    for y, loc, files, lang, cat, name in sorted(pts, key=lambda t: t[4]):
        color = CAT_COLOR.get(cat, "black")
        mark = {
            "mainstream":  "*",
            "specialized": "triangle*",
            "dsl-markup":  "square*",
            "legacy":      "diamond*",
            "esoteric":    "pentagon*",
        }.get(cat, "*")
        L.append(rf"  \addplot[only marks, color={color}, mark={mark}, mark options={{fill={color}}}] coordinates {{({loc},{y:.3f})}};")
        if cat not in seen_cat:
            L.append(rf"  \addlegendentry{{{CAT_LABEL[cat]}}}")
            seen_cat.add(cat)
        else:
            L.append(r"  \addlegendentry{}")

    # Add text annotations for notable outliers.
    for y, loc, files, lang, cat, name in pts:
        if name in ANNOTATE:
            anchor = "west" if loc < 50_000 else "east"
            xshift = "3pt" if anchor == "west" else "-3pt"
            L.append(rf"  \node[font=\tiny, anchor={anchor}, xshift={xshift}] at (axis cs:{loc},{y:.3f}) {{{ANNOTATE[name]}}};")

    L.append(r"\end{axis}")
    L.append(r"\end{tikzpicture}")
    L.append(r"\caption{Distribution of total repository size (LOC) per engine, grouped by language category. Each dot is one engine; the x-axis is logarithmic. Most engines cluster between 2\,k--12\,k lines; four repositories exceed 20\,k lines: the two LaTeX engines (one includes the full TeX macro expansion infrastructure), the two large esoteric-language projects (Brainfuck interpreters and test harnesses), and the CSS/HTML engine. The two annotated outliers exceed 40\,k lines due to included artefacts rather than engine source: \textit{chess-ruby-codex} contains PGN game databases; \textit{chess-why3-cc} includes generated C code emitted by the Why3 toolchain. Excluding these, the median is $\approx$4\,k LOC, with no systematic difference by category.}")
    L.append(r"\label{fig:loc-strip}")
    L.append(r"\end{figure}")

    out = FIG / "fig_loc_strip.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}  ({len(pts)} engines across {len(seen_cat)} categories)")


if __name__ == "__main__":
    main()
    emit_loc_strip()
