"""Emit a per-project Markdown report.

For each chess-* project, produce:
  reports/projects/<name>.md        human-readable evidence dossier
  data/projects/<name>.json         machine-readable appendix

The report contains:
  - Factual metadata (language, agent, period, LOC, git)
  - Chess feature coverage (what was implemented)
  - Session summary (prompts, tokens, cost, tools used)
  - User-driven backlog (BL-###) extracted from user prompts
  - Canonical "PL-ROOT" (first non-trivial human prompt)
  - Interaction analysis (categories of prompts, avg length)
  - Evidence pointers: [R:], [T:], [G:], [S:]

Usage:
  python3 scripts/per_project_report.py            # all projects
  python3 scripts/per_project_report.py chess-py   # one
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from common import (
    DATA_DIR,
    REPORTS_DIR,
    SANDBOX,
    compute_loc,
    detect_agent_suffix,
    discover_projects,
    fmt_ts,
    git,
    is_git_repo,
    primary_language,
    scan_features,
    short_quote,
)
import extract_sessions as sess


INTENT_PATTERNS = [
    ("FeatureRequest", re.compile(r"\b(add|implement|build|create|write|develop|introduce|make)\b", re.I)),
    ("BugFixRequest", re.compile(r"\b(fix|bug|broken|doesn'?t work|fails?|error|issue|regression)\b", re.I)),
    ("RefactorRequest", re.compile(r"\b(refactor|clean ?up|simplify|restructure|rename|split)\b", re.I)),
    ("TestRequest", re.compile(r"\btest(s|ing)?\b|perft|unit[- ]test", re.I)),
    ("Documentation", re.compile(r"\bdocument|readme|\bdocs?\b|explain|describe", re.I)),
    ("ToolingBuild", re.compile(r"\b(build|compile|makefile|cmake|cargo|gradle|install|setup|configure)\b", re.I)),
    ("Constraint", re.compile(r"\b(must|cannot|do not|don'?t|only|without|restrict|forbid|avoid)\b", re.I)),
    ("Question", re.compile(r"^\s*(how|why|what|where|when|which|who|can you|could you|do you)\b", re.I)),
    ("Scenario", re.compile(r"\b(play|game|position|opening|endgame|mate in|perft|match|tournament)\b", re.I)),
]


def classify_intent(text: str) -> list[str]:
    hits = []
    for name, pat in INTENT_PATTERNS:
        if pat.search(text):
            hits.append(name)
    if not hits:
        hits.append("Other")
    return hits


def load_project_data(project_dir: Path, codex_index) -> dict[str, Any]:
    loc = compute_loc(project_dir)
    feats_paths = scan_features(project_dir)
    feats_sum = {k: len(v) for k, v in feats_paths.items() if v}
    claude = sess.scan_claude_for_project(project_dir)
    codex_sessions = sess.filter_codex_for_project(codex_index, project_dir)
    codex = sess.aggregate_sessions(codex_sessions, agent="Codex")
    codex["sessions"] = codex_sessions
    git_info = {"is_git": is_git_repo(project_dir)}
    if git_info["is_git"]:
        git_info["log"] = git(["log", "--pretty=format:%h|%aI|%an|%s", "--no-merges"], project_dir).splitlines()
        git_info["n_commits"] = len(git_info["log"])
        git_info["authors"] = git(["shortlog", "-sne", "HEAD"], project_dir).splitlines()
    return {
        "name": project_dir.name,
        "path": str(project_dir),
        "loc": loc.__dict__,
        "primary_language": primary_language(loc),
        "features": feats_sum,
        "features_paths": feats_paths,
        "claude": claude,
        "codex": codex,
        "git": git_info,
    }


def collect_user_prompts(pdata: dict[str, Any]) -> list[dict[str, Any]]:
    prompts: list[dict[str, Any]] = []
    for s in pdata["claude"].get("sessions", []):
        for p in s.get("user_prompts", []):
            prompts.append({"ts": p["ts"], "text": p["text"], "agent": "Claude Code", "session": s["session_id"]})
    for s in pdata["claude"].get("subagents", []):
        for p in s.get("user_prompts", []):
            prompts.append({"ts": p["ts"], "text": p["text"], "agent": "Claude Code (subagent)", "session": s["session_id"]})
    for s in pdata["codex"].get("sessions", []):
        for p in s.get("user_prompts", []):
            prompts.append({"ts": p["ts"], "text": p["text"], "agent": "Codex", "session": s["session_id"]})
    # Sort by timestamp when available.
    prompts.sort(key=lambda x: (x["ts"] or ""))
    # Remove spam: Claude Code often re-sends tool outputs framed as user msgs;
    # filter messages that are clearly system/tool results.
    cleaned = []
    for p in prompts:
        t = p["text"]
        if not t:
            continue
        if t.startswith("<command-name>") or t.startswith("<local-command-stdout>"):
            continue
        if t.startswith("<task-notification>"):
            continue
        if t.startswith("Caveat: The messages below were generated by the user while running local commands"):
            continue
        if t.startswith("Please continue with") or t.startswith("Think harder") or t.startswith("[Request interrupted"):
            # These are still meaningful signals but we'll keep them to count
            pass
        cleaned.append(p)
    return cleaned


def render_md(pdata: dict[str, Any], out_path: Path) -> None:
    name = pdata["name"]
    path = pdata["path"]
    loc = pdata["loc"]
    feats = pdata["features"]
    prompts = collect_user_prompts(pdata)
    claude = pdata["claude"]
    codex = pdata["codex"]
    git_info = pdata["git"]

    agents = []
    if claude["n_sessions"] > 0:
        agents.append("Claude Code")
    if claude.get("subagent_sessions_count"):
        agents.append("Claude Code subagents")
    if codex["n_sessions"] > 0:
        agents.append("Codex")
    if not agents:
        g = detect_agent_suffix(name)
        if g:
            agents.append(g + " (inferred by name; no session transcript)")

    starts = [t for t in [claude.get("first_ts"), codex.get("first_ts")] if t]
    ends = [t for t in [claude.get("last_ts"), codex.get("last_ts")] if t]
    period = ""
    if starts:
        period = f"{fmt_ts(min(starts))} → {fmt_ts(max(ends))}"

    # Intent distribution
    intent_counter: Counter = Counter()
    lens = []
    for p in prompts:
        for label in classify_intent(p["text"]):
            intent_counter[label] += 1
        lens.append(len(p["text"]))
    avg_len = round(sum(lens) / len(lens), 1) if lens else 0

    # Output
    lines: list[str] = []
    lines.append(f"# {name}")
    lines.append("")
    lines.append(f"_Evidence-based dossier. Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}._")
    lines.append("")
    lines.append("## Phase 0 — Discovery")
    lines.append("")
    lines.append(f"- **Path:** `{path}` [R:{name}]")
    lines.append(f"- **Primary language:** {pdata['primary_language'] or '—'}")
    lines.append(f"- **Coding agent(s):** {', '.join(agents) or '—'}")
    lines.append(f"- **Period:** {period or '—'}")
    files_by_lang = loc.get("files_by_lang", {}) or {}
    loc_by_lang = loc.get("loc_by_lang", {}) or {}
    top_langs = sorted(loc_by_lang.items(), key=lambda x: -x[1])[:8]
    langs_fmt = ", ".join(f"{k} ({v} LOC, {files_by_lang.get(k,0)} files)" for k, v in top_langs) or "—"
    lines.append(f"- **LOC by language:** {langs_fmt}")
    lines.append(f"- **Totals:** {loc.get('total_files',0)} files, {loc.get('total_loc',0)} LOC [S:scan]")
    if git_info.get("is_git"):
        lines.append(f"- **Git:** {git_info.get('n_commits',0)} commits")
    else:
        lines.append("- **Git:** not a git repo")
    lines.append("")

    lines.append("## Phase 0 — Session artifacts")
    lines.append("")
    lines.append(f"- Claude Code sessions: {claude['n_sessions']} main + {claude.get('subagent_sessions_count',0)} subagent transcripts [T:{name}/claude]")
    lines.append(f"- Claude models seen: {', '.join(claude['models']) or '—'}")
    lines.append(f"- Codex sessions: {codex['n_sessions']} [T:{name}/codex]")
    lines.append(f"- Codex models seen: {', '.join(codex['models']) or '—'}")
    lines.append("")
    # Tokens
    ct = claude["cost"]["tokens_total"] if claude["cost"] else {}
    xt = codex["cost"]["tokens_total"] if codex["cost"] else {}
    lines.append("### Tokens & cost")
    lines.append("")
    lines.append("| Agent | Sessions | Prompts | Input | Output | Cache read | Cache create | USD (est.) |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    lines.append(
        f"| Claude Code | {claude['n_sessions']} | {claude['n_user_prompts']} "
        f"| {ct.get('input',0)} | {ct.get('output',0)} | {ct.get('cache_read',0)} | {ct.get('cache_creation',0)} "
        f"| ${claude['cost']['usd_estimate']:.2f} |"
    )
    lines.append(
        f"| Codex | {codex['n_sessions']} | {codex['n_user_prompts']} "
        f"| {xt.get('input',0)} | {xt.get('output',0)} | {xt.get('cache_read',0)} | — "
        f"| ${codex['cost']['usd_estimate']:.2f} |"
    )
    total_usd = claude['cost']['usd_estimate'] + codex['cost']['usd_estimate']
    lines.append(f"| **Total** |  |  |  |  |  |  | **${total_usd:.2f}** |")
    lines.append("")
    lines.append("_Cost is an estimate based on public per-model list prices; caches are charged at the discounted rate we observed._")
    lines.append("")

    # Chess features
    lines.append("## Chess-engine features detected")
    lines.append("")
    if feats:
        lines.append("| Feature | Matches | Sample path |")
        lines.append("|---|---:|---|")
        for k, n in sorted(feats.items(), key=lambda x: -x[1]):
            sample = (pdata["features_paths"].get(k) or ["—"])[0]
            lines.append(f"| {k} | {n} | `{sample}` |")
    else:
        lines.append("_No chess-specific patterns matched (feature scan is regex-based; check manually for unusual languages)._")
    lines.append("")

    # Tools
    if claude["tool_uses"] or codex["tool_uses"]:
        lines.append("## Agent tool usage (top 8)")
        lines.append("")
        merged: Counter = Counter()
        for k, v in (claude["tool_uses"] or {}).items():
            merged[("Claude", k)] = v
        for k, v in (codex["tool_uses"] or {}).items():
            merged[("Codex", k)] = v
        lines.append("| Agent | Tool | Count |")
        lines.append("|---|---|---:|")
        for (agent, tool), n in merged.most_common(12):
            lines.append(f"| {agent} | {tool} | {n} |")
        lines.append("")

    # Interaction
    lines.append("## Interaction profile")
    lines.append("")
    lines.append(f"- Total user prompts (both agents): **{len(prompts)}**")
    lines.append(f"- Avg prompt length: {avg_len} chars")
    if intent_counter:
        lines.append("- Intent distribution:")
        for k, n in intent_counter.most_common():
            lines.append(f"  - {k}: {n}")
    lines.append("")

    # PL-ROOT
    if prompts:
        lines.append("## Prompt ledger")
        lines.append("")
        lines.append("### PL-ROOT (first substantive user prompt)")
        for p in prompts:
            if len(p["text"]) >= 30:
                lines.append("")
                lines.append(f"_Agent: {p['agent']} — {fmt_ts(p['ts'])} — session `{p['session'][:8]}`_")
                lines.append("")
                lines.append("```")
                lines.append(p["text"][:1500])
                lines.append("```")
                break
        # Remaining prompts (abridged)
        lines.append("")
        lines.append("### Subsequent prompts (abridged)")
        lines.append("")
        lines.append("| # | Time | Agent | Intent | Prompt (truncated) |")
        lines.append("|---:|---|---|---|---|")
        for i, p in enumerate(prompts[1:60], start=2):
            ints = ",".join(classify_intent(p["text"])[:2])
            q = short_quote(p["text"], 140).replace("|", "\\|")
            lines.append(f"| {i} | {fmt_ts(p['ts'])} | {p['agent']} | {ints} | {q} |")
        if len(prompts) > 60:
            lines.append(f"| … | | | | _+{len(prompts)-60} more prompts_ |")
        lines.append("")

    # Git timeline
    if git_info.get("is_git"):
        lines.append("## Git timeline")
        lines.append("")
        log = git_info.get("log") or []
        if log:
            lines.append("| Hash | Date | Author | Subject |")
            lines.append("|---|---|---|---|")
            for row in log[:80]:
                parts = row.split("|", 3)
                if len(parts) == 4:
                    h, d, a, s = parts
                    s = s.replace("|", "\\|")
                    lines.append(f"| `{h}` | {d} | {a} | {short_quote(s, 120)} |")
            if len(log) > 80:
                lines.append(f"| … | | | _+{len(log)-80} more commits_ |")
        lines.append("")

    # User-driven backlog derivation
    lines.append("## User-driven feature backlog (best-effort, derived from prompts)")
    lines.append("")
    if not prompts:
        lines.append("_No user prompts recovered; backlog cannot be reconstructed from sessions._")
    else:
        bl_items = []
        seen_text = set()
        for p in prompts:
            text = p["text"].strip()
            if len(text) < 20:
                continue
            intents = classify_intent(text)
            if "Other" in intents and len(intents) == 1:
                continue
            if "Question" in intents and len(text) < 120:
                continue
            head = text.split("\n", 1)[0][:140]
            if head in seen_text:
                continue
            seen_text.add(head)
            bl_items.append({"ts": p["ts"], "agent": p["agent"], "intents": intents, "summary": short_quote(text, 180), "session": p["session"]})
        lines.append(f"Extracted **{len(bl_items)}** candidate backlog items. Each maps 1-1 to a user prompt and may consolidate with implementation commits.")
        lines.append("")
        for i, it in enumerate(bl_items[:40], start=1):
            lines.append(
                f"- **BL-{i:03d}** ({', '.join(it['intents'])}) [{fmt_ts(it['ts'])}] — {it['summary']} "
                f"[T:{it['agent']}/{it['session'][:8]}]"
            )
        if len(bl_items) > 40:
            lines.append(f"- _+{len(bl_items)-40} more items truncated in this view — see appendix._")
    lines.append("")

    lines.append("## Evidence pointers")
    lines.append("")
    lines.append(f"- [R:{name}] — repo at `{path}`")
    lines.append(f"- [T:{name}/claude] — Claude sessions at `~/.claude/projects/{os.path.basename(path)}...`")
    lines.append(f"- [T:{name}/codex] — Codex sessions filtered from `~/.codex/sessions/**.jsonl`")
    lines.append(f"- [S:scan] — `scripts/common.py::compute_loc` executed on {path}")
    lines.append("")
    lines.append("## Limitations")
    lines.append("")
    miss = claude.get("missing_from_index") or []
    if miss:
        lines.append(f"- {len(miss)} Claude Code session transcripts referenced by `sessions-index.json` but missing on disk (likely archived).")
    lines.append("- Cost estimates assume list prices and ignore Anthropic/OpenAI account discounts.")
    lines.append("- Chess feature detection uses regex; languages with unusual syntax (Brainfuck, APL, assembler) can be under-detected.")
    lines.append("- User backlog is derived from user-authored prompts; constraints and acceptance criteria are often implicit.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def save_appendix(pdata: dict[str, Any], out_path: Path) -> None:
    appendix = {
        "name": pdata["name"],
        "path": pdata["path"],
        "primary_language": pdata["primary_language"],
        "loc": pdata["loc"],
        "features": pdata["features"],
        "feature_paths": pdata["features_paths"],
        "claude": {
            "n_sessions": pdata["claude"]["n_sessions"],
            "subagent_sessions_count": pdata["claude"].get("subagent_sessions_count", 0),
            "n_user_prompts": pdata["claude"]["n_user_prompts"],
            "n_assistant_messages": pdata["claude"]["n_assistant_messages"],
            "models": pdata["claude"]["models"],
            "tool_uses": pdata["claude"]["tool_uses"],
            "cost": pdata["claude"]["cost"],
            "first_ts": pdata["claude"]["first_ts"],
            "last_ts": pdata["claude"]["last_ts"],
            "missing_from_index": pdata["claude"].get("missing_from_index", []),
            "sessions": [
                {
                    "session_id": s["session_id"],
                    "first_ts": s.get("first_ts"),
                    "last_ts": s.get("last_ts"),
                    "models": s.get("models"),
                    "turns": s.get("turns"),
                    "n_events": s.get("num_events"),
                    "tokens": s.get("tokens"),
                    "tool_uses": s.get("tool_uses"),
                    "first_prompt_sample": (s.get("user_prompts") or [{"text": ""}])[0].get("text", "")[:300],
                }
                for s in pdata["claude"].get("sessions", [])
            ],
        },
        "codex": {
            "n_sessions": pdata["codex"]["n_sessions"],
            "n_user_prompts": pdata["codex"]["n_user_prompts"],
            "n_assistant_messages": pdata["codex"]["n_assistant_messages"],
            "models": pdata["codex"]["models"],
            "tool_uses": pdata["codex"]["tool_uses"],
            "cost": pdata["codex"]["cost"],
            "first_ts": pdata["codex"]["first_ts"],
            "last_ts": pdata["codex"]["last_ts"],
            "sessions": [
                {
                    "session_id": s["session_id"],
                    "first_ts": s.get("first_ts"),
                    "last_ts": s.get("last_ts"),
                    "models": s.get("models"),
                    "turns": s.get("turns"),
                    "tokens": s.get("tokens"),
                    "tool_uses": s.get("tool_uses"),
                    "first_prompt_sample": (s.get("user_prompts") or [{"text": ""}])[0].get("text", "")[:300],
                }
                for s in pdata["codex"].get("sessions", [])
            ],
        },
        "git": pdata["git"],
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(appendix, indent=2, default=str))


def main(argv: list[str]) -> None:
    print("Indexing Codex sessions…")
    codex_index = sess.scan_codex_index()
    print(f"  {len(codex_index)} Codex sessions indexed")
    if argv:
        # Resolve each argv entry: could be a folder name or a nested logical name.
        all_targets = {name: path for name, path in discover_projects()}
        targets = [(a, all_targets.get(a) or (SANDBOX / a)) for a in argv]
    else:
        targets = discover_projects()
    reports_dir = REPORTS_DIR / "projects"
    data_dir = DATA_DIR / "projects"
    reports_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    for logical, p in targets:
        if not p.exists():
            print(f"skip: {p}")
            continue
        print(f"→ {logical}")
        try:
            pdata = load_project_data(p, codex_index)
            pdata["name"] = logical  # use canonical name for nested engines
        except Exception as e:
            print(f"  !! {e}")
            continue
        render_md(pdata, reports_dir / f"{logical}.md")
        save_appendix(pdata, data_dir / f"{logical}.json")


if __name__ == "__main__":
    main(sys.argv[1:])
